import * as THREE from 'https://esm.sh/three@0.165.0';
import { OrbitControls } from 'https://esm.sh/three@0.165.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://esm.sh/three@0.165.0/examples/jsm/loaders/GLTFLoader.js';
const MODEL_URL='./models/Casa_mejor.glb';
const $=id=>document.getElementById(id);const canvas=$('viewer'), card=document.querySelector('.viewerCard'), msg=$('message'), dot=$('statusDot'), loader=$('loader'), err=$('errorBox');
function setStatus(t,type='ready'){msg.textContent=t;dot.classList.remove('loading','error');if(type==='loading')dot.classList.add('loading');if(type==='error')dot.classList.add('error')}
function show(el,v){el.classList.toggle('hidden',!v)}
function canUseWebGL(){try{const c=document.createElement('canvas');return !!(window.WebGLRenderingContext&&(c.getContext('webgl')||c.getContext('experimental-webgl')))}catch(e){return false}}
if(!canUseWebGL()){setStatus('Esta TV/navegador no soporta WebGL.','error');show(loader,false);show(err,true);throw new Error('WebGL no disponible')}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x090b17);scene.fog=new THREE.Fog(0x090b17,18,70);
const camera=new THREE.PerspectiveCamera(42,1,.01,5000);camera.position.set(8,5.2,8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.enablePan=true;controls.screenSpacePanning=true;controls.autoRotate=true;controls.autoRotateSpeed=.5;
scene.add(new THREE.HemisphereLight(0xeaf0ff,0x202436,2.3));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(8,12,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const fill=new THREE.DirectionalLight(0x9edcff,1.2);fill.position.set(-8,5,-7);scene.add(fill);
let initialCamera=null, keyboardMoveEnabled=true;const pressed=new Set();const clock=new THREE.Clock();
function fit(root){const box=new THREE.Box3().setFromObject(root);const center=box.getCenter(new THREE.Vector3());root.position.sub(center);const box2=new THREE.Box3().setFromObject(root);root.position.y-=box2.min.y;const size=box2.getSize(new THREE.Vector3());const max=Math.max(size.x,size.y,size.z)||1;const dist=(max/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))))*1.55;camera.position.set(dist*.95,dist*.62,dist*.95);controls.target.set(0,size.y*.35,0);controls.minDistance=dist*.12;controls.maxDistance=dist*8;controls.update();initialCamera={pos:camera.position.clone(),target:controls.target.clone()}}
async function load(){try{setStatus('Cargando modelo simple...','loading');const gltf=await Promise.race([new GLTFLoader().loadAsync(MODEL_URL),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),25000))]);gltf.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material.side=THREE.DoubleSide;o.material.needsUpdate=true}}});scene.add(gltf.scene);fit(gltf.scene);show(loader,false);setStatus('Modelo simple cargado correctamente.')}catch(e){console.error(e);show(loader,false);show(err,true);setStatus('Error al cargar el modelo simple.','error')}}
function resize(){const w=card.clientWidth,h=card.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function updateMove(dt){if(!keyboardMoveEnabled||pressed.size===0)return;const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()>0)forward.normalize();const right=new THREE.Vector3().crossVectors(forward,camera.up).normalize();const move=new THREE.Vector3();if(pressed.has('arrowup')||pressed.has('w'))move.add(forward);if(pressed.has('arrowdown')||pressed.has('s'))move.sub(forward);if(pressed.has('arrowright')||pressed.has('d'))move.add(right);if(pressed.has('arrowleft')||pressed.has('a'))move.sub(right);if(move.lengthSq()===0)return;move.normalize().multiplyScalar((pressed.has('shift')?5:2.1)*dt);camera.position.add(move);controls.target.add(move);controls.update()}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','shift'].includes(k)){e.preventDefault();pressed.add(k)}});window.addEventListener('keyup',e=>pressed.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>pressed.clear());
$('resetView').addEventListener('click',()=>{if(!initialCamera)return;camera.position.copy(initialCamera.pos);controls.target.copy(initialCamera.target);controls.update()});$('toggleRotate').addEventListener('click',e=>{controls.autoRotate=!controls.autoRotate;e.target.textContent='Auto-rotación: '+(controls.autoRotate?'On':'Off')});$('toggleKeyboardMove').addEventListener('click',e=>{keyboardMoveEnabled=!keyboardMoveEnabled;pressed.clear();e.target.textContent='Movimiento libre: '+(keyboardMoveEnabled?'On':'Off')});
window.addEventListener('resize',resize);function animate(){requestAnimationFrame(animate);updateMove(clock.getDelta());controls.update();renderer.render(scene,camera)}resize();animate();load();
